### ISSUE TITLE
ModuleNotFoundError: No module named 'retro_star.model'

### ISSUE THREAD

**Issue by Jh-SYSU** [binghong-ml/retro_star#1]
Great Work!

Hi, I'm trying to reproduce the results with Retro_star  in the linked paper. It seems no retro_star.model in the source code. Can you update it?
"ModuleNotFoundError: No module named 'retro_star.model'"

Thanks a lot!

**Comment by binghong-ml** [comment]
Thanks for noticing this! The bug is fixed. Let me know if it works.

**Comment by Jh-SYSU** [comment]
Thanks!
