### ISSUE TITLE
Dataset splits

### ISSUE THREAD

**Issue by aielawady** [binghong-ml/retro_star#13]
Hello! Thank you for your work and for sharing the code.

I can't find the train/dev/test sets used in the paper. Is there a link to the splits or a script to reproduce the same sets to train the single step model?

**Comment by binghong-ml** [comment]
Hi, thanks for your interest in our work!

Retro* assumes a well-trained one-step model. It can be arbitrarily trained using your own data.

Or you can our provided data here:
https://www.dropbox.com/sh/39a7wo0k26r5lld/AAAdineUgbu_NRSxEwaQwg7Ea?dl=0

**Comment by aielawady** [comment]
Thank you!
