### ISSUE TITLE
Template extractor missing

### ISSUE THREAD

**Issue by laurent3577** [binghong-ml/retro_star#14]
Thank you very much for sharing your code on this great work.

I'm interested in your preprocessing of the USPTO dataset to extract the reaction templates that will be used to train the expansion policy model.

I tried following the procedure detailed here: https://github.com/binghong-ml/retro_star/tree/master/retro_star/packages/rdchiral/templates

But when running:

`$ python clean_and_extract_uspto.py`

I got an error that the `template_extractor` module is missing:
```
❯ python clean_and_extract_uspto.py
Traceback (most recent call last):
  File "clean_and_extract_uspto.py", line 14, in <module>
    import template_extractor
ModuleNotFoundError: No module named 'template_extractor'
```

Which indeed I can't find on the repo.

I would be grateful if you could provide the code for that module too.

Thank you.

**Comment by binghong-ml** [comment]
Please refer to https://github.com/Hanjun-Dai/GLN/tree/master/gln/data_process for template extraction. Thanks!
